---
# File: configure-backup.yml
# Type: task
# Part: MongoDB

- name: MongoDB | Deploy backup crontab
  template: src=cron.daily_automongobackup.j2 dest=/etc/cron.daily/automongobackup owner=root group=root mode=0644
- name: MongoDB | Deploy backup defaults
  template: src=default_automongobackup.j2 dest=/etc/default/automongobackup owner=root group=root mode=0644
- name: MongoDB | Deploy backup script
  copy: src=sbin_automongobackup dest=/usr/sbin/automongobackup owner=root group=root mode=0755